### ISSUE TITLE
example on node2vec

### ISSUE THREAD

**Issue by matricer** [Tencent/plato#23]
any example on node2vec including running scripts, graph data and so on.

**Comment by skyssj** [comment]
matricer, 

Sorry, we don't have any doc about node2vec-randomwalk for now. Currently you can modify [this_script](https://github.com/Tencent/plato/blob/master/scripts/run_pagerank.sh) to run node2vec-randomwalk. Also you can get some information about input params by `node2vec_randomwalk --help`(or refer to the parameters' definition in the [source code](https://github.com/Tencent/plato/blob/master/example/node2vec_randomwalk.cc)).  The input graph can be a file or a directory of files in [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) format, eg(the third column of weight is optional):
```c++
0,1,0.123
4,3,1.2
```

**Comment by matricer** [comment]
@skyssj thx
I follow your instructions and it works. There come some questions about node2vec-randomwalk.
Q1: what does "--rate" mean?
Q2: does this code work for both directed and undirected graph?
Q3: "--is_weighted=false" means ignoring the edges' weight or ignoring p and q?

**Comment by skyssj** [comment]
matricer,

A1: `--rate` is a memory consumption optimization option which value is between (0, 1] , the lower the value the lower the memory consumption. The basic idea is instead of start all walkers(each walker take some memory for keep their state, eg: footprints etc. ) at the very beginning, we start rate% walkers per one BSP.

A2: No, Node2vec is defined on the  undirected graph. This code take undirected graph(which means only A->B or B->A can exited in the input) as its input and add reversed edge automatically.

A3: "--is_weighted=false" means ignoring the edges' weight.

**Comment by matricer** [comment]
@skyssj problem solved! thx~
