### ISSUE TITLE
peak memory will double when shuffle edges (after partition)

### ISSUE THREAD

**Issue by yetingsky** [Tencent/plato#34]

**Comment by yetingsky** [comment]
Instead of loading all edges into cache, maybe we could read edges from HDFS again.

**Comment by xuguruogu** [comment]
```
template <typename EDATA, typename VID_T = vid_t, template<typename, typename> class CACHE = edge_block_cache_t>
std::shared_ptr<bcsr_t<EDATA, sequence_balanced_by_source_t>> create_bcsr_seqs_from_path
```

Yes, we have encountered this problem before. Actually, only a few algorithms are so sensitive to memory usage. We chose to use `edge_file_cache_t` instead of loading from HDFS again. Which mmap cache memory to disk storage, performance will not be affected if memory is big enough.

Tips on how to use `edge_file_cache_t`:

replace

```
plato::create_***_from_path<edge_t, VDATA>(...)
```

to

```
plato::create_***_from_path<edge_t, VDATA, plato::edge_file_cache_t>(...)
```

**Comment by yetingsky** [comment]
> ```
> template <typename EDATA, typename VID_T = vid_t, template<typename, typename> class CACHE = edge_block_cache_t>
> std::shared_ptr<bcsr_t<EDATA, sequence_balanced_by_source_t>> create_bcsr_seqs_from_path
> ```
> 
> Yes, we have encountered this problem before. Actually, only a few algorithms are so sensitive to memory usage. We chose to use `edge_file_cache_t` instead of loading from HDFS again. Which mmap cache memory to disk storage, performance will not be affected if memory is big enough.
> 
> Tips on how to use `edge_file_cache_t`:
> 
> replace
> 
> ```
> plato::create_***_from_path<edge_t, VDATA>(...)
> ```
> 
> to
> 
> ```
> plato::create_***_from_path<edge_t, VDATA, plato::edge_file_cache_t>(...)
> ```

OK，I will try this.

**Comment by yetingsky** [comment]
BTW，a lot of graph structure in plato (e.g. bcsr, dcsc)，how different are they，which one is most memory efficient？

**Comment by xuguruogu** [comment]
> @xuguruogu BTW，a lot of graph structure in plato (e.g. bcsr, dcsc)，how different are they，which one is most memory efficient？

This needs lots of words to explain clearly. The best way to fully understand the design is reading paper [Gemini](https://coolerzxw.github.io/data/publications/gemini_osdi16.pdf)[1].

Simply speaking, the basic storage structures are `CSR` and `CSC`. The key of graph computing is to make a tradeoff between memory usage and network bandwidth. Dualmode-engine, including `push` and `pull`, is proposed. Structure `CSR` is essential for `push`, and  `CSC` is essential for `pull`.

For some algorithms, such as CC(Connected Component ), due to active vertices are change during computing progress, dualmode-engine choose `push` or `pull` automatically after counting active vertex number. Structure `CSR` and `CSC` are both needed, as `push` and `pull` are both used. 

For other algorithms, take pagerank for example, all vertices are active during the iteration. Choose `pull` is best practice. Thus we only need structure `CSC`.

Other graph structures, such as `tcsr` and `cbcsr`, are only used in specific circumstance.

[1] Xiaowei Zhu, Wenguang Chen, Weimin Zheng, Xiaosong Ma. Gemini: A computation-centric distributed graph processing system. 12th USENIX Symposium on Operating Systems Design and Implementation (OSDI ’16)

**Comment by yetingsky** [comment]
thx ~
